name = "dhamet-api"
main = "src/index.js"
compatibility_date = "2026-07-01"
workers_dev = false


routes = [
  { pattern = "ouglsoft.com/dhamet/api/*", zone_name = "ouglsoft.com" }
]

[[d1_databases]]
binding = "DB"
database_name = "dhamet2_test"
database_id = "3f957678-fd6c-4164-8302-f5fa4b8acf16"
migrations_dir = "migrations"


[[durable_objects.bindings]]
name = "REALTIME"
class_name = "RealtimeObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RealtimeObject"]

[vars]
PUBLIC_BASE_PATH = "/dhamet"
APP_ORIGIN = "https://ouglsoft.com/dhamet"
RESEND_FROM_EMAIL = "Dhamet <noreply@ouglsoft.com>"
EXPRESS_TURN_HOST = "relay1.expressturn.com:3478"
TURN_TTL_SECONDS = "3600"
DHAMET_BACKUP_URL = "https://dhamet2.ouglsoft.com/pages/loby.html?emergency=1"













